name: 'Deploy'

concurrency:
  group: prod_deploy
  cancel-in-progress: false

on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-20.04
    if: github.actor != 'dependabot[bot]' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
    steps:
      - uses: actions/checkout@v3.5.2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - uses: badsyntax/github-action-aws-cloudformation@v1.0.3
        name: Update CloudFormation Stack
        id: update-stack
        with:
          stack-name: 'badsyntax-github-action-example-aws-cloudfront'
          template: './cloudformation/s3-cloudfront.yml'
          apply-change-set: ${{ github.event_name != 'repository_dispatch' }}
          aws-region: 'us-east-1'
          parameters: |
            S3BucketName=badsyntax-github-action-example-aws-cloudfront-us-east-1&
            S3AllowedOrigins=https://cloudfront-action.richardwillis.info&
            CloudFrontRootHosts=cloudfront-action.richardwillis.info&
            CertificateARN=arn:aws:acm:us-east-1:008215002370:certificate/cfb34309-b9bb-4f63-9af3-51026b8107d6

      - uses: badsyntax/github-action-aws-s3@v1.0.1
        name: Sync mutable HTML files to S3
        id: sync-html-s3
        with:
          bucket: ${{ steps.update-stack.outputs.S3BucketName }}
          action: 'sync'
          src-dir: './out'
          files-glob: '**/*.html'
          aws-region: 'us-east-1'
          prefix: 'root'
          strip-extension-glob: '**/**.html'
          cache-control: 'public,max-age=0,s-maxage=31536000,must-revalidate'

      - uses: badsyntax/github-action-aws-s3@v1.0.1
        name: Sync immutable files to S3
        id: sync-immutable-s3
        with:
          bucket: ${{ steps.update-stack.outputs.S3BucketName }}
          action: 'sync'
          src-dir: './out'
          files-glob: 'css/**'
          aws-region: 'us-east-1'
          prefix: 'root'
          cache-control: 'public,max-age=31536000,immutable'

      - uses: ./
        name: Invalidate CloudFront Cache
        id: invalidate-cloudfront-cache
        with:
          distribution-id: ${{ steps.update-stack.outputs.CFDistributionId }}
          aws-region: 'us-east-1'
          origin-prefix: 'root'
          invalidate-paths: ${{ steps.sync-html-s3.outputs.S3SyncedFiles }}
          default-root-object: 'index'
          include-origin-prefix: true
